{% set name = "pesviewer" %}
{% set version = "1.1.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/zadorlab/PESViewer/archive/{{ version }}.tar.gz
    sha256: b61ff2c367f1fa9594e31765be7cd24a199eb911d9d40bb6b12c030fbf4519db

build:
    noarch: python
    script: {{ PYTHON }} -m pip install . -vv
    number: 0
    entry_points:
        - pesviewer = pesviewer.pesviewer:main

requirements:
    host:
        - python >=3.8
        - pip
    run:
        - python >=3.8
        - numpy >=1.19.0
        - matplotlib
        - networkx
        - pillow
        - rdkit
        - openbabel
        - pyvis


test:
    imports:
        - pesviewer
    commands:
        - pip check
    requires:
        - pip
       
about:
    home: https://github.com/zadorlab/PESViewer
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: "Potential Energy Surface Visualizer"

    description: |
        PESViewer is a code to depict and analyze a potential energy surface 
        characterized by wells, bimolecular products, transition states and 
        barrierless reactions.
    doc_url: https://github.com/zadorlab/PESViewer/wiki
    dev_url: https://github.com/zadorlab/PESViewer

extra:
    recipe-maintainers:
        - cmartia
        - juditzador
